Starting Database API Server...
Database path: /Users/ugurulger/Desktop/Adalex/database/api/../files.db
 * Serving Flask app 'api_endpoint'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.178.50:5001
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 684-185-872
Starting Database API Server...
Database path: /Users/ugurulger/Desktop/Adalex/database/api/../files.db
Traceback (most recent call last):
  File "/Users/ugurulger/Desktop/Adalex/database/api/api_endpoint.py", line 968, in <module>
    app.run(debug=True, port=5001, host='0.0.0.0')
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ugurulger/Desktop/Adalex/database/api/venv/lib/python3.13/site-packages/flask/app.py", line 889, in run
    run_simple(t.cast(str, host), port, self, **options)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ugurulger/Desktop/Adalex/database/api/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 1097, in run_simple
    run_with_reloader(
    ~~~~~~~~~~~~~~~~~^
        srv.serve_forever,
        ^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        reloader_type=reloader_type,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/ugurulger/Desktop/Adalex/database/api/venv/lib/python3.13/site-packages/werkzeug/_reloader.py", line 446, in run_with_reloader
    ensure_echo_on()
    ~~~~~~~~~~~~~~^^
  File "/Users/ugurulger/Desktop/Adalex/database/api/venv/lib/python3.13/site-packages/werkzeug/_reloader.py", line 426, in ensure_echo_on
    termios.tcsetattr(sys.stdin, termios.TCSANOW, attributes)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
termios.error: (4, 'Interrupted system call')
